import { writeFileSync, mkdirSync } from "node:fs";
import { basename, join } from "node:path";
import type { InferenceOptions, InferenceResult } from "./inference.js";
import type { AgentOptions, AgentResult } from "./agent.js";
import { estimateCost } from "./pricing.js";

/**
 * Deterministic, offline stand-ins for the Claude inference + agent runners.
 * They synthesize plausible, input-derived outputs (so caching and diffs behave
 * exactly as they would with a real model) and stream progress — which makes
 * the whole product demoable with no API key. Enable with `--mock` / LOOM_MOCK.
 */

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Per-chunk streaming delay; set LOOM_MOCK_DELAY=0 for instant (tests). */
function chunkDelay(): number {
  const v = Number(process.env.LOOM_MOCK_DELAY);
  return Number.isFinite(v) ? v : 22;
}

function approxTokens(s: string): number {
  return Math.max(1, Math.round(s.length / 4));
}

function extract(prompt: string) {
  const lines = prompt.split("\n").map((l) => l.trim());
  const bullets = lines.filter((l) => /^[-*]\s+/.test(l)).map((l) => l.replace(/^[-*]\s+/, ""));
  const heads = lines.filter((l) => /^#{1,6}\s+/.test(l)).map((l) => l.replace(/^#+\s+/, ""));
  const sentences = lines.filter((l) => l.length > 40 && !l.startsWith("#") && !/^[-*]/.test(l));
  return { bullets, heads, sentences };
}

// Structural headers the prompt assembler injects ("## inputs/market.md",
// "## (step) analysis") read as filler if they leak into a synthesized title.
function isStructuralHeading(h: string): boolean {
  return /^\((step|context)\)/.test(h) || /[\\/]/.test(h) || /\.[a-z0-9]{1,4}$/i.test(h);
}
function pickTitle(heads: string[], fallback: string): string {
  return heads.find((h) => !/^context$/i.test(h) && !isStructuralHeading(h)) || fallback;
}
// Cheap deterministic hash so each step picks a different slice of points —
// otherwise every artifact in a pipeline repeats the same first six bullets.
function seedOf(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0;
  return h;
}

function synthesize(opts: InferenceOptions): string {
  const { bullets, heads, sentences } = extract(opts.prompt);
  const title = pickTitle(heads, "Synthesized Brief");
  const pool = bullets.length ? bullets : sentences;
  const start = pool.length ? seedOf(opts.prompt) % pool.length : 0;
  const points = pool.length
    ? Array.from({ length: Math.min(6, pool.length) }, (_, i) => pool[(start + i) % pool.length])
    : [];
  const out: string[] = [];
  out.push(`# ${title}`);
  out.push("");
  out.push(sentences[0] || "A concise synthesis of the provided source material.");
  out.push("");
  out.push("## Key points");
  if (points.length) for (const p of points) out.push(`- ${p.replace(/[.\s]+$/, "")}.`);
  else out.push("- No structured points were found in the source material.");
  out.push("");
  out.push("## Recommendation");
  out.push(
    `Focus on the highest-leverage item above and validate it next` +
      `${opts.effort ? ` (effort: ${opts.effort})` : ""}.`,
  );
  out.push("");
  out.push(`> _Generated by Loom in mock mode using ${opts.model}._`);
  return out.join("\n");
}

export async function mockInference(opts: InferenceOptions): Promise<InferenceResult> {
  const content = synthesize(opts);
  const chunks = content.match(/[\s\S]{1,40}/g) ?? [content];
  const d = chunkDelay();
  for (const ch of chunks) {
    opts.onDelta?.(ch);
    if (d) await sleep(d);
  }
  const inputTokens = approxTokens(opts.prompt) + approxTokens(opts.system ?? "");
  const outputTokens = approxTokens(content);
  return {
    content,
    usage: { inputTokens, outputTokens, costUsd: estimateCost(opts.model, inputTokens, outputTokens) },
  };
}

export async function mockAgent(opts: AgentOptions): Promise<AgentResult> {
  const d = chunkDelay();
  const lines = opts.prompt.split("\n").map((l) => l.trim());
  const heads = lines.filter((l) => /^#{1,6}\s+/.test(l)).map((l) => l.replace(/^#+\s+/, ""));
  // Prefer the product name for a landing page — an upstream document's heading
  // ("Customer interviews") reads as filler on the "agent-built" page.
  const title = opts.titleHint?.trim() || pickTitle(heads, "Generated Site");
  // The blurb should come from the upstream artifact's body, not from the
  // agent's own instruction line — take the first prose line after a heading.
  const firstHead = lines.findIndex((l) => /^#{1,6}\s+/.test(l));
  const blurb =
    lines
      .slice(firstHead >= 0 ? firstHead + 1 : 0)
      .find((l) => l.length > 40 && !l.startsWith("#") && !l.startsWith(">") && !/^[-*]\s/.test(l)) ||
    "Built from the upstream artifact.";

  const progress = [
    "Reading the upstream spec…",
    "Planning the file layout…",
    "Writing index.html…",
    "Writing styles.css…",
    "Verifying output…",
  ];
  for (const p of progress) {
    opts.onText?.(p + "\n");
    if (d) await sleep(d);
  }

  mkdirSync(opts.cwd, { recursive: true });
  const html = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title><link rel="stylesheet" href="styles.css" /></head>
<body>
  <main>
    <h1>${escapeHtml(title)}</h1>
    <p>${escapeHtml(blurb)}</p>
    <a class="cta" href="#">Get started</a>
  </main>
</body>
</html>
`;
  const css = `:root{--accent:#c2643c}
*{box-sizing:border-box}
body{font:18px/1.6 system-ui,sans-serif;margin:0;background:#f4f1ea;color:#1c2024}
main{max-width:680px;margin:12vh auto;padding:0 1.2rem}
h1{font-size:2.4rem;margin:0 0 .6rem}
.cta{display:inline-block;margin-top:1.4rem;background:var(--accent);color:#fff;padding:.7rem 1.3rem;border-radius:10px;text-decoration:none}
`;
  writeFileSync(join(opts.cwd, "index.html"), html);
  writeFileSync(join(opts.cwd, "styles.css"), css);
  const created = ["index.html", "styles.css"];

  const report =
    `# Agent report\n\n` +
    `Built a self-contained landing page in \`${basename(opts.cwd)}/\`.\n\n` +
    `**Files created**\n` +
    created.map((f) => `- \`${f}\``).join("\n") +
    `\n\nThe page headlines **${title}** and renders standalone (open \`index.html\`).`;

  const inputTokens = approxTokens(opts.prompt);
  const outputTokens = approxTokens(report) + 300;
  return {
    content: report,
    usage: { inputTokens, outputTokens, costUsd: estimateCost(opts.model, inputTokens, outputTokens) },
    subtype: "success",
  };
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** The runner pair to pass to `new Engine(ws, dirs, store, mockRunners())`. */
export function mockRunners() {
  return { inference: mockInference, agent: mockAgent };
}
